import type { Metadata } from "next";
import { Inter } from "next/font/google";
 import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ActiveSectionContextProvider from "@/context/useacive-section";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className="dark !scroll-smooth ">
      <body className={inter.className}>
        <div className="w-full h-full relative">
          {children}
        </div>

      </body>
    </html>
  );
}
